name: Version Bump, Changelog and Release workflow
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  version-changelog-and-release:
    name: Bump version, generate changelog, and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine bump level
        id: bump-level
        run: |
          git log --format=%B -n 1 ${{ github.sha }} | 
          awk '
          /^BREAKING CHANGE:/ || /^[a-zA-Z]+(\([a-zA-Z]+\))?!:/ {print "major"; exit}
          /^feat:/ {print "minor"; exit}
          /^fix:/ || /^doc:/ || /^perf:/ || /^refactor:/ || /^style:/ || /^test:/ {print "patch"; exit}
          /^chore\(release\): prepare for/ || /^chore\(deps.*\):/ || /^chore\(pr\):/ || /^chore\(pull\):/ {print "skip"; exit}
          /^chore:/ || /^ci:/ {print "patch"; exit}
          /security/ {print "patch"; exit}
          /^revert:/ {print "patch"; exit}
          END {if (NR==0) print "patch"}
          ' > bump_level.txt
          echo "level=$(cat bump_level.txt)" >> $GITHUB_OUTPUT
      
      - name: Bump version
        uses: haya14busa/action-bumpr@v1
        id: bumpr
        with:
          default_bump_level: ${{ steps.bump-level.outputs.level }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: "steps.bumpr.outputs.skip != 'true'"
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: ${{ steps.bumpr.outputs.next_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
