name: Version Bump, Changelog and Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  version-changelog-and-release:
    name: Bump version, generate changelog, and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Bump version
        uses: tomerfi/version-bumper-action@2.0.1
        id: bumper

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: "${{ steps.bumper.outputs.next != '' }}"
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ steps.bumper.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
