name: Version Bump, Changelog, and Release

on:
  push:
    branches:
      - main  # Change this to `main` if your default branch is `main`

jobs:
  version-changelog-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate a changelog
        id: generate_changelog
        run: |
          git cliff --config cliff.toml -vv --latest --strip header > CHANGES.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ${{ steps.generate_changelog.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
