# name: Version Bump, Changelog, and Releases
# on:
#   push:
#     branches:
#       - main
# permissions:
#   contents: write
# jobs:
#   version-changelog-and-release:
#     name: Bump version, generate changelog, and create release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Increment version
#         id: increment-version
#         uses: RichardInnocent/semantic-versioning-git@v0.0.1

#       - name: Print if version changed
#         if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
#         run: echo "The new version is now $new_version"
#         env:
#           new_version: ${{ steps.increment-version.outputs.new-version }}

#       - name: Generate a changelog
#         uses: orhun/git-cliff-action@v3
#         id: git-cliff
#         with:
#           config: cliff.toml
#           args: -vv --latest --strip header
#         env:
#           GITHUB_REPO: ${{ github.repository }}

#       - name: Create Release
#         uses: softprops/action-gh-release@v1
#         if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
#         with:
#           body: ${{ steps.git-cliff.outputs.content }}
#           tag_name: ${{ steps.increment-version.outputs.new-version }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
